### ISSUE TITLE
2023-02-08 Meeting

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/conglobo#19]
# TODO
- [x] #20
- [x] Check in on #8 
- [x] Check in on #2 
- [x] Review k8s progress #13 
- [x] Check in with Flutter in Dev containers (talk about moving to web app) #15 
- [x] Check in with Python in Dev containers, #16 
- [x] Talk about next steps

# NEXT STEPS
* Sprint 1: We should create basic Flutter + Flask app (as a Docker image)
