### ISSUE TITLE
Todo: Due by 2023-03-29

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/conglobo#37]
- [x] #34 (after this meeting)
- [x] #39
- [x] #40
- [ ] #33
- [ ] #42
- [ ] #41
- [ ] #46 
- [ ] #43 
- [x] Service: VS Code In Browser
- [ ] Service: Machine Learning
- [ ] Service: File sync
