### ISSUE TITLE
2023-03-08 Meeting

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/conglobo#38]
# Todo
- [x] Discuss [new plan](https://github.com/ehharvey/conglobo/wiki/Plan)
- [x] Check in on #34 
- [x] #36 
- [x] Discuss design for #22 
- [x] Discuss design for #33

# Action Items
- #37

**Comment by ehharvey** [comment]
Today: Work on intergration for base management app
Tomorrow: work on Service enable/disable implementation
